// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGiJqVOv5I0oq2tYMEmcSAkXHvnVyPZpk',
    appId: '1:406573912610:web:663251daa12d859369f07b',
    messagingSenderId: '406573912610',
    projectId: 'home-automation-81701',
    authDomain: 'home-automation-81701.firebaseapp.com',
    databaseURL: 'https://home-automation-81701-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-81701.appspot.com',
    measurementId: 'G-0893DZF5DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpD3JmrL-ZSzSuWDaonqSM0y_89xnNx8w',
    appId: '1:406573912610:android:ba9bbc273ca6ab7269f07b',
    messagingSenderId: '406573912610',
    projectId: 'home-automation-81701',
    databaseURL: 'https://home-automation-81701-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-81701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmEEOi9FujFWYdxUdRLPw3b2LfBuA0TTg',
    appId: '1:406573912610:ios:fb4dee5d4a738cf069f07b',
    messagingSenderId: '406573912610',
    projectId: 'home-automation-81701',
    databaseURL: 'https://home-automation-81701-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-81701.appspot.com',
    androidClientId: '406573912610-16qlf1mjif19mivbn7bjhnv04m0dc3ka.apps.googleusercontent.com',
    iosClientId: '406573912610-lstkdpsdd19rdakic189206i2jpdmqdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bldeviceConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmEEOi9FujFWYdxUdRLPw3b2LfBuA0TTg',
    appId: '1:406573912610:ios:fb4dee5d4a738cf069f07b',
    messagingSenderId: '406573912610',
    projectId: 'home-automation-81701',
    databaseURL: 'https://home-automation-81701-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-81701.appspot.com',
    androidClientId: '406573912610-16qlf1mjif19mivbn7bjhnv04m0dc3ka.apps.googleusercontent.com',
    iosClientId: '406573912610-lstkdpsdd19rdakic189206i2jpdmqdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bldeviceConnection',
  );
}
